export const mockAvailableLendingBooks = [
  {
    id: 1001,
    bookId: 11,
    title: "الفيزياء الجامعية",
    author: "سيرواي",
    owner: "محمد علي",
    status: "متاح",
    stateKey: "Available",
  },
  {
    id: 1002,
    bookId: 12,
    title: "التفاضل والتكامل",
    author: "ستيوارت",
    owner: "سارة خالد",
    status: "متاح",
    stateKey: "Available",
  },
  {
    id: 1003,
    bookId: 13,
    title: "هياكل البيانات",
    author: "سيدجويك",
    owner: "أحمد سامي",
    status: "متاح",
    stateKey: "Available",
  },
  {
    id: 1004,
    bookId: 14,
    title: "علم الأدوية",
    author: "ليبينكوت",
    owner: "منى حسين",
    status: "متاح",
    stateKey: "Available",
  },
  {
    id: 1005,
    bookId: 15,
    title: "الذكاء الاصطناعي",
    author: "راسل ونورفيج",
    owner: "يوسف أحمد",
    status: "متاح",
    stateKey: "Available",
  },
];

export const mockBorrowingRequests = [
  {
    id: 501,
    lendingRecordId: 1001,
    bookTitle: "الفيزياء الجامعية",
    requestDate: "2026-04-20T10:00:00Z",
    expectedReturnDate: "2026-05-01T10:00:00Z",
    status: "Pending",
  },
  {
    id: 502,
    lendingRecordId: 1002,
    bookTitle: "التفاضل والتكامل",
    requestDate: "2026-04-18T10:00:00Z",
    expectedReturnDate: "2026-04-29T10:00:00Z",
    status: "Approved",
  },
  {
    id: 503,
    lendingRecordId: 1003,
    bookTitle: "علم الأدوية",
    requestDate: "2026-04-10T10:00:00Z",
    expectedReturnDate: "2026-04-18T10:00:00Z",
    status: "Completed",
  },
  {
    id: 504,
    lendingRecordId: 1004,
    bookTitle: "هندسة البرمجيات",
    requestDate: "2026-04-12T10:00:00Z",
    expectedReturnDate: "2026-04-22T10:00:00Z",
    status: "Rejected",
  },
];

export const mockMyCopies = [
  {
    id: 701,
    bookId: 21,
    title: "إحصاء تطبيقي",
    author: "عبد الرحمن سلامة",
    condition: 1,
    state: "Available",
    isOnLendingList: true,
    bookCoverImageUrl: "",
  },
  {
    id: 702,
    bookId: 22,
    title: "مبادئ المحاسبة",
    author: "مها محمود",
    condition: 2,
    state: "Available",
    isOnLendingList: false,
    bookCoverImageUrl: "",
  },
  {
    id: 703,
    bookId: 23,
    title: "شبكات الحاسوب",
    author: "خالد أمين",
    condition: 0,
    state: "Borrowed",
    isOnLendingList: true,
    bookCoverImageUrl: "",
  },
  {
    id: 704,
    bookId: 24,
    title: "مقدمة في القانون",
    author: "هشام عبد اللطيف",
    condition: 3,
    state: "Available",
    isOnLendingList: false,
    bookCoverImageUrl: "",
  },
];
